name = "bignum"
version = "0.1.0"
defaultTargets = ["Bignum"]
lintDriver = "batteries/runLinter"
testDriver = "BignumTest"
requiresModuleSystem = true

[leanOptions]
#autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"

[[require]]
name = "mathlib"
scope = "leanprover-community"

# [[require]]
# name = "cslib"
# scope = "leanprover"

[[lean_lib]]
name = "Bignum"

[[lean_lib]]
name = "BignumTest"
globs = ["BignumTest.+"]
